<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>promise</title>
    <style>
        *{
            margin:0;
            padding:0;
        }
    </style>
</head>
<body>
<script>
    var body = document.body;
    //异步加载图片
    function loadImageAsync(url) {
        return new Promise(function(resolve, reject) {
            const image = new Image();

            image.onload = function() {
                resolve(image);
            };

            image.onerror = function() {
                reject(new Error('Could not load image at ' + url));
            };

            image.src = url;
        });
    }

    loadImageAsync("http://imgcache.gtimg.cn/vipstyle/game/act/zj/266241/img/start-btn.png").then(function(json){
        body.appendChild(json);
    }).catch(function(error){
        console.log(error);
    })

    var count = 10;
    var p1 = new Promise((resolve,reject) => resolve(function(){
            count+=10;
        }));
    var p2 = new Promise((resolve,reject) => resolve(p1));
    p2.then(function(json){
        json();
        console.log(count);
    })


    //调用resolve(1)以后，后面的console.log(2)还是会执行并且会首先打印出来。
    //因为立即resolved的Promise是在本轮事件循环的末尾执行，总是晚于本轮循环的同步任务。
    new Promise((resolve, reject) => {
        resolve(1);
        console.log(2);
    }).then(r => {
        console.log(r);
    }); // 2  1

    var num = 1;
    var data = new Promise((resolve,reject) => resolve(num));
    data.then(json => {
        console.log(json);
        return json;
    }).then(json => console.log(json));


    const promise = new Promise((resolve,reject) =>{throw new Error("test")});
    promise.then((json)=>console.log(json))
           .catch(error=>console.log(error));

    //Promise在resolve语句后面，再抛出错误，不会被捕获，等于没抛出。因为Promise状态一旦改变，就永久保持该状态，不会再变了。
    const promise1 = new Promise(function(resolve, reject) {
        resolve('ok');
        throw new Error('test');
    });
    promise1.then(function(value) { console.log(value) }) //ok
           .catch(function(error) { console.log(error) });


    const someAsyncThing = function(){
        return new Promise((resolve,reject) => resolve(x+2));
    }
    someAsyncThing().then(()=>console.log("everything is great"))
        .catch(error => console.log(error));
    setTimeout(()=>console.log(123),2000);

    //用Promise对象实现的Ajax操作例子
    const getJSON = function(url){
        var promise = new Promise(function(resolve,reject){
            var handler = function(){
                if(this.readyState !== 4){
                    return;
                }
                if(this.status === 200){
                    resolve(this.response);
                }else{
                    reject(new Error(this.statusText));
                }
            };
            var client = new XMLHttpRequest();
            client.open("GET",url);
            client.onreadystatechange = handler;
            client.responseType = "json";
            client.setRequestHeader("Accept","application/json");
            client.send();
        });
        return promise;
    };

    getJSON("/posts.json").then(function(json){
        console.log("Contents: " + json);
    },function(error){
        console.log("出错了",error);
    })
</script>
</body>
</html>